### ISSUE TITLE
Errors while running the project

### ISSUE THREAD

**Issue by shatran** [BBB/dropzone-redux-form-example#1]
Hi @BBB and thanks for this project!
I tried to clone and run it, but at first i get 404 on these:
GET http://localhost:3000/build/vendor.css 
GET http://localhost:3000/build/app.css 
choosing/dragging a file does nothing, and hitting 'Submit' get me these:

Fetch API cannot load http://example.com/send/. No 'Access-Control-Allow-Origin' header is present on the requested resource.
App.js?a673:33 TypeError: Failed to fetch(…

Maybe i don't understand the purpose of the example, but i don't see any use of form validation/errors regarding dropzone.
I'll be happy to get some guidance about how to use your example.

**Comment by BBB** [comment]
@shatran those 404 errors were just because there's no css in the example. I've removed the offending includes.

The example just shows how to pull the value out of the `<Dropzone />` component, there are other examples that show how to do field validation with redux-form. 

The error you're seeing on submit is to be expected as well; you'll need to switch the POST endpoint to the once associated with your app for it to work.

I hope that clears things up

**Comment by shatran** [comment]
Thanks @BBB!. any chance you used asyncValidate to validate the file was uploaded successfully?

**Comment by BBB** [comment]
@shatran Sorry I've not used that.
